# Generated by Django 3.2.6 on 2021-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlalias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlalias',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
