# Generated by Django 3.2.6 on 2021-10-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlalias', '0003_urlaliastest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlaliastest',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='urlaliastest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='urlaliastest',
            name='visitas',
        ),
        migrations.AlterField(
            model_name='urlaliastest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
