# Generated by Django 3.2.6 on 2021-10-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlalias', '0004_auto_20211023_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLAliasTest',
        ),
    ]
